[2025-01-26T06:31:30.747+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T06:31:30.819+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T06:24:15.002026+00:00 [None]>
[2025-01-26T06:31:30.858+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T06:24:15.002026+00:00 [None]>
[2025-01-26T06:31:30.863+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 6
[2025-01-26T06:31:30.937+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-26 06:24:15.002026+00:00
[2025-01-26T06:31:30.957+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=271) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T06:31:30.968+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2025-01-26T06:31:30.973+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'manual__2025-01-26T06:24:15.002026+00:00', '--job-id', '532', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpl561eio3']
[2025-01-26T06:31:30.987+0000] {standard_task_runner.py:105} INFO - Job 532: Subtask create_table
[2025-01-26T06:31:34.198+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T06:31:35.092+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T06:31:35.149+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
